### ISSUE TITLE
Incomplete DM mapping

### ISSUE THREAD

**Issue by Tohka-aryani** [TindakMalaysia/Selangor-Maps#1]
Size of ECMAP at end is 0 
{}
Write to Shapefile!!
NEW/Unmatched DM! ==> 093/03/19
NEW/Unmatched DM! ==> 094/06/15
NEW/Unmatched DM! ==> 094/06/16
NEW/Unmatched DM! ==> 094/07/19
NEW/Unmatched DM! ==> 097/13/09
NEW/Unmatched DM! ==> 097/14/14
NEW/Unmatched DM! ==> 097/14/15
NEW/Unmatched DM! ==> 097/15/16
NEW/Unmatched DM! ==> 099/19/11
NEW/Unmatched DM! ==> 099/20/18
NEW/Unmatched DM! ==> 100/21/18
NEW/Unmatched DM! ==> 101/24/18

I'm looking for these two for boundary mapping, but its unavailable.
NEW/Unmatched DM! ==> 094/06/15
NEW/Unmatched DM! ==> 094/06/16

Is it possible to update these maps?

**Comment by daneshchacko** [comment]
First of all the Daerah Mengundi Boundaries of Selangor is valid until end of 2015. This map file is strictly for GE13 purposes. Any spatial data request post 2015, you would need to purchase it from us

**Comment by Tohka-aryani** [comment]
Can I have your contact details? I would like to purchase the data from you.

**Comment by daneshchacko** [comment]
Kindly email to danesh@tindakmalaysia.com so that we best understand your requirements
